myList = [4, 3, 5.8, False, "hola"]
print(myList)
myList.append(8)
print(myList)
myList.append(9)
print(myList)
myList.extend(range(10,13))
print(myList)
conteo = myList.count(3)
print(conteo)
myList.insert(9, True)
print(myList)
myList.remove(12)
print(myList)